#!/bin/bash

#mkdir datasets
#mkdir workloads

mkdir results
mkdir results/microbench
mkdir results/microbench/sample_size_sweep
mkdir results/microbench/cpr_latency
mkdir results/microbench/hu_tucker
mkdir results/microbench/array_trie
mkdir results/microbench/ht_vs_dc
mkdir results/microbench/build_time_breakdown
mkdir results/SuRF
mkdir results/SuRF/point
mkdir results/SuRF/range
mkdir results/SuRF_real
mkdir results/SuRF_real/point
mkdir results/SuRF_real/range
mkdir results/ART
mkdir results/ART/point
mkdir results/ART/range
mkdir results/btree
mkdir results/btree/point
mkdir results/btree/range
mkdir results/hot
mkdir results/hot/point
mkdir results/hot/range
mkdir results/prefixbtree
mkdir results/prefixbtree/point
mkdir results/prefixbtree/range

mkdir figures
mkdir figures/microbench
mkdir figures/microbench/sample_size_sweep
mkdir figures/microbench/cpr_latency
mkdir figures/microbench/hu_tucker
mkdir figures/microbench/array_trie
mkdir figures/microbench/ht_vs_dc
mkdir figures/microbench/build_time_breakdown
mkdir figures/SuRF
mkdir figures/SuRF/point
mkdir figures/SuRF/range
mkdir figures/SuRF_real
mkdir figures/SuRF_real/point
mkdir figures/SuRF_real/range
mkdir figures/ART
mkdir figures/ART/point
mkdir figures/ART/range
mkdir figures/btree
mkdir figures/btree/point
mkdir figures/btree/range
mkdir figures/hot
mkdir figures/hot/point
mkdir figures/hot/range
mkdir figures/prefixbtree
mkdir figures/prefixbtree/point
mkdir figures/prefixbtree/range
